
export default new Map([
["src/data/authors/main-author/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fdata%2Fauthors%2Fmain-author%2Findex.mdx&astroContentModuleFlag=true")],
["src/data/blog/en/chalk-scraping-across-the-board/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fdata%2Fblog%2Fen%2Fchalk-scraping-across-the-board%2Findex.mdx&astroContentModuleFlag=true")],
["src/data/blog/en/example-three/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fdata%2Fblog%2Fen%2Fexample-three%2Findex.mdx&astroContentModuleFlag=true")],
["src/data/blog/en/example-two/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fdata%2Fblog%2Fen%2Fexample-two%2Findex.mdx&astroContentModuleFlag=true")],
["src/data/blog/en/pencil-case-full-of-stubby-pencils/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fdata%2Fblog%2Fen%2Fpencil-case-full-of-stubby-pencils%2Findex.mdx&astroContentModuleFlag=true")],
["src/data/blog/en/tailwind-gradient-underline/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fdata%2Fblog%2Fen%2Ftailwind-gradient-underline%2Findex.mdx&astroContentModuleFlag=true")],
["src/data/blog/en/tsconfig-paths-setup/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fdata%2Fblog%2Fen%2Ftsconfig-paths-setup%2Findex.mdx&astroContentModuleFlag=true")],
["src/data/blog/zh/example-one/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fdata%2Fblog%2Fzh%2Fexample-one%2Findex.mdx&astroContentModuleFlag=true")],
["src/data/blog/zh/example-two/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fdata%2Fblog%2Fzh%2Fexample-two%2Findex.mdx&astroContentModuleFlag=true")],
["src/data/blog/zh/tsconfig-paths-setup/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fdata%2Fblog%2Fzh%2Ftsconfig-paths-setup%2Findex.mdx&astroContentModuleFlag=true")],
["src/data/blog/zh/best-vscode-extensions-front-end-developers/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fdata%2Fblog%2Fzh%2Fbest-vscode-extensions-front-end-developers%2Findex.mdx&astroContentModuleFlag=true")],
["src/data/otherPages/zh/elements/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fdata%2FotherPages%2Fzh%2Felements%2Findex.mdx&astroContentModuleFlag=true")],
["src/data/otherPages/zh/privacy-policy/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fdata%2FotherPages%2Fzh%2Fprivacy-policy%2Findex.mdx&astroContentModuleFlag=true")],
["src/data/otherPages/en/elements/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fdata%2FotherPages%2Fen%2Felements%2Findex.mdx&astroContentModuleFlag=true")],
["src/data/otherPages/en/privacy-policy/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fdata%2FotherPages%2Fen%2Fprivacy-policy%2Findex.mdx&astroContentModuleFlag=true")],
["src/data/blog/zh/tailwind-gradient-underline/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fdata%2Fblog%2Fzh%2Ftailwind-gradient-underline%2Findex.mdx&astroContentModuleFlag=true")],
["src/data/blog/zh/example-three/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fdata%2Fblog%2Fzh%2Fexample-three%2Findex.mdx&astroContentModuleFlag=true")]]);
		