
import __ASTRO_IMAGE_IMPORT_Bc6d1 from "../main-author/avatar.png?astroContentImageFlag=&importer=src%2Fdata%2Fauthors%2Fmain-author%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_VU65f from "../chalk-scraping-across-the-board/heroImage.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Fen%2Fchalk-scraping-across-the-board%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_Z1uqB56 from "../example-three/heroImage.png?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Fen%2Fexample-three%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_Z1PsyBi from "../example-two/heroImage.png?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Fen%2Fexample-two%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_XY0Aq from "../pencil-case-full-of-stubby-pencils/heroImage.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Fen%2Fpencil-case-full-of-stubby-pencils%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_292bWt from "../tailwind-gradient-underline/heroImage.png?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Fen%2Ftailwind-gradient-underline%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_1OusJx from "../tsconfig-paths-setup/heroImage.png?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Fen%2Ftsconfig-paths-setup%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_Z1wxBlc from "../example-one/heroImage.png?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Fzh%2Fexample-one%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_f3HSB from "../example-two/heroImage.png?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Fzh%2Fexample-two%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_1fH1Ye from "../tsconfig-paths-setup/heroImage.png?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Fzh%2Ftsconfig-paths-setup%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_Z9mPlp from "../best-vscode-extensions-front-end-developers/heroImage.png?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Fzh%2Fbest-vscode-extensions-front-end-developers%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_c7b6Q from "../tailwind-gradient-underline/heroImage.png?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Fzh%2Ftailwind-gradient-underline%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_Z13pTAI from "../example-three/heroImage.png?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Fzh%2Fexample-three%2Findex.mdx";
export default new Map([["../main-author/avatar.png?astroContentImageFlag=&importer=src%2Fdata%2Fauthors%2Fmain-author%2Findex.mdx", __ASTRO_IMAGE_IMPORT_Bc6d1], ["../chalk-scraping-across-the-board/heroImage.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Fen%2Fchalk-scraping-across-the-board%2Findex.mdx", __ASTRO_IMAGE_IMPORT_VU65f], ["../example-three/heroImage.png?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Fen%2Fexample-three%2Findex.mdx", __ASTRO_IMAGE_IMPORT_Z1uqB56], ["../example-two/heroImage.png?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Fen%2Fexample-two%2Findex.mdx", __ASTRO_IMAGE_IMPORT_Z1PsyBi], ["../pencil-case-full-of-stubby-pencils/heroImage.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Fen%2Fpencil-case-full-of-stubby-pencils%2Findex.mdx", __ASTRO_IMAGE_IMPORT_XY0Aq], ["../tailwind-gradient-underline/heroImage.png?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Fen%2Ftailwind-gradient-underline%2Findex.mdx", __ASTRO_IMAGE_IMPORT_292bWt], ["../tsconfig-paths-setup/heroImage.png?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Fen%2Ftsconfig-paths-setup%2Findex.mdx", __ASTRO_IMAGE_IMPORT_1OusJx], ["../example-one/heroImage.png?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Fzh%2Fexample-one%2Findex.mdx", __ASTRO_IMAGE_IMPORT_Z1wxBlc], ["../example-two/heroImage.png?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Fzh%2Fexample-two%2Findex.mdx", __ASTRO_IMAGE_IMPORT_f3HSB], ["../tsconfig-paths-setup/heroImage.png?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Fzh%2Ftsconfig-paths-setup%2Findex.mdx", __ASTRO_IMAGE_IMPORT_1fH1Ye], ["../best-vscode-extensions-front-end-developers/heroImage.png?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Fzh%2Fbest-vscode-extensions-front-end-developers%2Findex.mdx", __ASTRO_IMAGE_IMPORT_Z9mPlp], ["../tailwind-gradient-underline/heroImage.png?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Fzh%2Ftailwind-gradient-underline%2Findex.mdx", __ASTRO_IMAGE_IMPORT_c7b6Q], ["../example-three/heroImage.png?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2Fzh%2Fexample-three%2Findex.mdx", __ASTRO_IMAGE_IMPORT_Z13pTAI]]);
		